site_name: PTX Compliance Research
theme: readthedocs
nav:
  - Home: index.md
  - Catalog:
    - Catalog Overview: catalog/index.md
  - Contract:
    - Contract Overview: contract/index.md
    - Mediator Protocol: contract/mediator-protocol.md
    - Connector Requirements: contract/contract-connector-requirements.md
plugins:
    - search
    - mermaid2
    - git-revision-date-localized:
        type: date
repo_url: https://github.com/VisionsOfficial/idsa-gaia-edc-minimal-compatibility
edit_uri: blob/main/docs/
copyright: Copyright © 2024 Visions