name: Merge main into gh-pages

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Checkout gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages

    - name: Merge main into gh-pages
      run: |
        git merge origin/main --no-ff --no-edit --allow-unrelated-histories

      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-mermaid2-plugin
        pip install mkdocs-material
        pip install mkdocs-git-revisions-date-localized-plugin

    - name: Build MkDocs
      run: |
        mkdocs build --clean --config-file mkdocs.yml
        mv site/* .
        rm -rf site

    - name: Add Git files
      run: |
        git add .
        git commit -m "[CI] Merge main into gh-pages"
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin gh-pages